In [36]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [37]:
pip install ucimlrepo

Note: you may need to restart the kernel to use updated packages.


In [38]:
from ucimlrepo import fetch_ucirepo
energy_efficiency = fetch_ucirepo(id=242)

In [39]:
import math

In [40]:
X = energy_efficiency.data.features 
y = energy_efficiency.data.targets
print(energy_efficiency.metadata)
print(energy_efficiency.variables) 

{'uci_id': 242, 'name': 'Energy Efficiency', 'repository_url': 'https://archive.ics.uci.edu/dataset/242/energy+efficiency', 'data_url': 'https://archive.ics.uci.edu/static/public/242/data.csv', 'abstract': 'This study looked into assessing the heating load and cooling load requirements of buildings (that is, energy efficiency) as a function of building parameters.', 'area': 'Computer Science', 'tasks': ['Classification', 'Regression'], 'characteristics': ['Multivariate'], 'num_instances': 768, 'num_features': 8, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': ['Y1', 'Y2'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2012, 'last_updated': 'Mon Feb 26 2024', 'dataset_doi': '10.24432/C51307', 'creators': ['Athanasios Tsanas', 'Angeliki Xifara'], 'intro_paper': {'ID': 379, 'type': 'NATIVE', 'title': 'Accurate quantitative estimation of energy performance of residential buildings using statistical machine 

In [41]:
X

X1     X2     X3      X4   X5  X6   X7  X8
0    0.98  514.5  294.0  110.25  7.0   2  0.0   0
1    0.98  514.5  294.0  110.25  7.0   3  0.0   0
2    0.98  514.5  294.0  110.25  7.0   4  0.0   0
3    0.98  514.5  294.0  110.25  7.0   5  0.0   0
4    0.90  563.5  318.5  122.50  7.0   2  0.0   0
..    ...    ...    ...     ...  ...  ..  ...  ..
763  0.64  784.0  343.0  220.50  3.5   5  0.4   5
764  0.62  808.5  367.5  220.50  3.5   2  0.4   5
765  0.62  808.5  367.5  220.50  3.5   3  0.4   5
766  0.62  808.5  367.5  220.50  3.5   4  0.4   5
767  0.62  808.5  367.5  220.50  3.5   5  0.4   5

[768 rows x 8 columns]

In [42]:
y

Y1     Y2
0    15.55  21.33
1    15.55  21.33
2    15.55  21.33
3    15.55  21.33
4    20.84  28.28
..     ...    ...
763  17.88  21.40
764  16.54  16.88
765  16.44  17.11
766  16.48  16.61
767  16.64  16.03

[768 rows x 2 columns]

In [43]:
X = np.array(X)
y = np.array(y)

In [44]:
X

array([[9.800e-01, 5.145e+02, 2.940e+02, ..., 2.000e+00, 0.000e+00,
        0.000e+00],
       [9.800e-01, 5.145e+02, 2.940e+02, ..., 3.000e+00, 0.000e+00,
        0.000e+00],
       [9.800e-01, 5.145e+02, 2.940e+02, ..., 4.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [6.200e-01, 8.085e+02, 3.675e+02, ..., 3.000e+00, 4.000e-01,
        5.000e+00],
       [6.200e-01, 8.085e+02, 3.675e+02, ..., 4.000e+00, 4.000e-01,
        5.000e+00],
       [6.200e-01, 8.085e+02, 3.675e+02, ..., 5.000e+00, 4.000e-01,
        5.000e+00]])

In [45]:
X_normal = (X - X.mean(axis=0))/X.std(axis=0)

In [46]:
X_normal

array([[ 2.04177671, -1.78587489, -0.56195149, ..., -1.34164079,
        -1.76044698, -1.81457514],
       [ 2.04177671, -1.78587489, -0.56195149, ..., -0.4472136 ,
        -1.76044698, -1.81457514],
       [ 2.04177671, -1.78587489, -0.56195149, ...,  0.4472136 ,
        -1.76044698, -1.81457514],
       ...,
       [-1.36381225,  1.55394308,  1.12390297, ..., -0.4472136 ,
         1.2440492 ,  1.41133622],
       [-1.36381225,  1.55394308,  1.12390297, ...,  0.4472136 ,
         1.2440492 ,  1.41133622],
       [-1.36381225,  1.55394308,  1.12390297, ...,  1.34164079,
         1.2440492 ,  1.41133622]])

In [47]:
y

array([[15.55, 21.33],
       [15.55, 21.33],
       [15.55, 21.33],
       ...,
       [16.44, 17.11],
       [16.48, 16.61],
       [16.64, 16.03]])

In [48]:
def compute_cost(X, y, w, b):
    m = X.shape[0]
    cost = 0.0

    for i in range(m):
        y_pred = np.dot(X[i], w) + b
        err_i = (y_pred - y[i]) ** 2
        cost += err_i
    cost = cost/2 * m
    return cost

In [49]:
def compute_gradient(X, y, w, b):
    m, n = X.shape
    dj_dw = np.zeros((n,))
    dj_db = 0

    for i in range(m):
        y_pred = np.dot(X[i], w) + b
        err_i = y_pred - y[i]
        for j in range(n):
            dj_dw[j] = dj_dw[j] + (err_i * X[i, j])
        dj_db += err_i
    dj_dw = dj_dw/m
    dj_db = dj_db/m
    return dj_dw, dj_db

In [50]:
def gradient_descent(X, y, w_ini, b_ini, alpha, iters):
    j_history = []
    w = w_ini
    b = b_ini

    for i in range(iters):
        dj_dw, dj_db = compute_gradient(X, y, w, b)

        w = w - alpha * dj_dw
        b = b - alpha * dj_db
        
        if i < 100000:
            j_history.append(compute_cost(X, y, w, b))

        if i% math.ceil(iters / 10) == 0:
            print(f"Iteration {i:4d} Cost {j_history[-1]:8.2f}")
            
    return w, b, j_history

In [53]:
def polynomial_features(X, degree):
    X_poly = X.copy()
    for d in range(2, degree + 1):
        X_poly = np.hstack([X_poly, X**d])
    return X_poly

In [54]:
X_poly = polynomial_features(X_normal, 2)

In [55]:
X

array([[9.800e-01, 5.145e+02, 2.940e+02, ..., 2.000e+00, 0.000e+00,
        0.000e+00],
       [9.800e-01, 5.145e+02, 2.940e+02, ..., 3.000e+00, 0.000e+00,
        0.000e+00],
       [9.800e-01, 5.145e+02, 2.940e+02, ..., 4.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [6.200e-01, 8.085e+02, 3.675e+02, ..., 3.000e+00, 4.000e-01,
        5.000e+00],
       [6.200e-01, 8.085e+02, 3.675e+02, ..., 4.000e+00, 4.000e-01,
        5.000e+00],
       [6.200e-01, 8.085e+02, 3.675e+02, ..., 5.000e+00, 4.000e-01,
        5.000e+00]])

In [56]:
X_normal

array([[ 2.04177671, -1.78587489, -0.56195149, ..., -1.34164079,
        -1.76044698, -1.81457514],
       [ 2.04177671, -1.78587489, -0.56195149, ..., -0.4472136 ,
        -1.76044698, -1.81457514],
       [ 2.04177671, -1.78587489, -0.56195149, ...,  0.4472136 ,
        -1.76044698, -1.81457514],
       ...,
       [-1.36381225,  1.55394308,  1.12390297, ..., -0.4472136 ,
         1.2440492 ,  1.41133622],
       [-1.36381225,  1.55394308,  1.12390297, ...,  0.4472136 ,
         1.2440492 ,  1.41133622],
       [-1.36381225,  1.55394308,  1.12390297, ...,  1.34164079,
         1.2440492 ,  1.41133622]])

In [58]:
X_poly[1, :]

array([ 2.04177671, -1.78587489, -0.56195149, -1.47007664,  1.        ,
       -0.4472136 , -1.76044698, -1.81457514,  4.16885215,  3.18934911,
        0.31578947,  2.16112532,  1.        ,  0.2       ,  3.09917355,
        3.29268293])

In [51]:
y_1 = y[:, 0]

In [60]:
m, n = X.shape
w_init = np.zeros(X_poly.shape[1])
b_init = 0
epoch = 100000
alpha = 1e-3
w_final, b_final, J_history = gradient_descent(X_poly, y_1, w_init, b_init, alpha, epoch)
print(f" Gradient descent found best w, b  at w: {w_final} and b:{b_final} ")

for i in range(m):
    print(f"Prediction: {(np.dot(X_poly[i], w_final) + b_final):.2f} Actual output: {y_1[i]}")

Iteration    0 Cost 173948727.13
Iteration 10000 Cost 2526820.62
Iteration 20000 Cost 2353032.76
Iteration 30000 Cost 2335999.28
Iteration 40000 Cost 2324290.24
Iteration 50000 Cost 2314400.83
Iteration 60000 Cost 2305663.85
Iteration 70000 Cost 2297832.74
Iteration 80000 Cost 2290773.25
Iteration 90000 Cost 2284387.80
 Gradient descent found best w, b  at w: [-4.75303413e-01 -1.54977286e-01  2.34484470e+00 -1.28358498e+00
  7.35349602e+00 -2.60816366e-02  2.53660033e+00  1.77915037e-01
 -3.03631167e-01 -1.18769652e+00 -4.22736138e-01  1.10008839e+00
  1.20259391e+01 -1.00312031e-02 -4.89742911e-01 -4.34957199e-01] and b:12.025939070334159 
Prediction: 20.75 Actual output: 15.55
Prediction: 20.74 Actual output: 15.55
Prediction: 20.72 Actual output: 15.55
Prediction: 20.68 Actual output: 15.55
Prediction: 24.09 Actual output: 20.84
Prediction: 24.08 Actual output: 21.46
Prediction: 24.06 Actual output: 20.71
Prediction: 24.02 Actual output: 19.68
Prediction: 21.94 Actual output: 19.5
P

In [66]:
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

In [ ]:
plt.plot(J_history)
plt.ylabel("Cost j(w, b)")
plt.xlabel("Iteration")
plt.title("Cost Vs Iteration")
plt.show()